## MongoDB Express configuration
mongoexpress:
  ingress:
    host: mongoexpress-dev.biester.vip

## general
ingress:
  className: traefik
volume:
  storageClassName: local-path
  storageClassNameEnabled: true

## Hedgedoc configuration
hedgedoc:
  nodeSelector:
  ingress:
    host: hedgedoc-dev.biester.vip
    tlsEnabled: true

treasury:
  nodeSelector:
  ingress:
    host: treasury-dev.biester.vip
    tlsEnabled: true

