apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: treasury
  namespace: {{ .Values.treasury.nameSpace}}
spec:
  ingressClassName: {{ .Values.ingress.className }}
{{- if .Values.treasury.ingress.tlsEnabled }}
  tls:
    - hosts:
        - {{ .Values.treasury.ingress.host }}
      secretName: {{ .Values.treasury.secrets }}
{{- end }}
  rules:
    - host: {{ .Values.treasury.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: treasury
                port:
                  number: 80